Repository SyntaxUI/syntaxui, pull requests merged in 2024-05, with the labels that each got.

#118 feat: shimmer button
  credits.md
  src/app/docs/components/button/shimmer-button/page.mdx
  src/showcase/components/button/ShimmerButton.tsx
  src/showcase/ui-group/ButtonCards.tsx
Labels: enhancement

#120 docs: added documentation to code components
  src/components/code/Code.tsx
  src/components/code/CodeGroup.tsx
  src/components/code/CodeGroupFromFile.tsx
  src/components/code/ComponentPreview.tsx
  src/components/code/PreviewCodeGroup.tsx
Labels: documentation

#123 Add check for `button` click in `onBlur` handler
  src/app/docs/components/input/page.mdx
  src/showcase/components/input/TagInput.tsx
Labels: documentation

#141 Updated ID for Sring Animated Feature Component
  src/showcase/components/features/SpringAnimatedFeatures.tsx
Labels: bug

#140 Add: labeled toggle
  credits.md
  src/app/docs/components/toggle/labeled-toggle/page.mdx
  src/app/docs/components/toggle/neubrutalism-toggle/page.mdx
  src/showcase/components/toggle/LabeledToggle.tsx
  src/showcase/components/toggle/NeubrutalismToggle.tsx
  src/showcase/components/toggle/SimpleToggle.tsx
  src/showcase/ui-group/ToggleCards.tsx
Labels: enhancement

#145 feat: used framer-motion layout to simplify toggle component
  src/showcase/components/toggle/SimpleToggle.tsx
Labels: enhancement

#133 feat: Add New Shine Button
  credits.md
  src/app/docs/components/button/shine-button/page.mdx
  src/showcase/components/button/ShineButton.tsx
  src/showcase/ui-group/ButtonCards.tsx
Labels: enhancement

#174 ✨ added AnimatedLogoCloud
  src/app/(docs)/components/logo-cloud/page.mdx
  src/components/Navigation.tsx
  src/components/code/ComponentPreview.tsx
  src/showcase/components/logo-cloud/AnimatedLogoCloud.tsx
  src/showcase/ui-group/ComponentCards.tsx
  tailwind.config.ts
Labels: enhancement

#177 fix: BorderGlowButton only Tailwind
  src/app/(docs)/components/button/border-glow-button/page.mdx
  src/showcase/components/button/BorderGlowButton.tsx
Labels: enhancement

#182 feat: added greeting workflow 🤖
  .github/workflows/greetings.yml
Labels: enhancement

#196 Add: Slide Toggle
  credits.md
  src/app/(docs)/components/toggle/slide-toggle/page.mdx
  src/showcase/components/toggle/SlideToggle.tsx
  src/showcase/ui-group/ToggleCards.tsx
Labels: enhancement
