Repository SyntaxUI/syntaxui, pull requests merged in 2024-04, with the labels that each got.

#39 style: use tabular-nums for text ticker wrapper
  src/app/docs/components/text/page.mdx
  src/components/PreviewCode/Text.tsx
Labels: bug, enhancement

#42 feat: Added a new tabs variants
  package-lock.json
  src/app/docs/components/tabs/page.mdx
  src/app/docs/page.mdx
  src/components/PreviewCode/IconTabs.tsx
  src/components/PreviewCode/LineTabs.tsx
  src/ui/Tabs.tsx
Labels: enhancement

#53 Added Toggle section with a normal toggle switch / updated credits to reflect addition
  README.md
  src/app/docs/components/toggle/page.mdx
  src/app/docs/components/toggle/toggle/page.mdx
  src/app/docs/page.mdx
  src/components/Cards/ToggleCards.tsx
  src/components/ComponentCards.tsx
  src/components/Navigation.tsx
  src/components/PreviewCode/Toggle.tsx
Labels: enhancement

#62 Refactor: component imports to use lowercase folder names and changed…
  src/app/docs/animations/hovers/jiggle/page.mdx
  src/app/docs/animations/hovers/page.mdx
  src/app/docs/animations/hovers/pop/page.mdx
  src/app/docs/animations/hovers/tada/page.mdx
  src/app/docs/animations/hovers/vibrate/page.mdx
  src/app/docs/animations/skewed-infinite-scroll/page.mdx
  src/app/docs/components/button/heartbeat-button/page.mdx
  src/app/docs/components/button/page.mdx
  src/app/docs/components/button/stitches-button/page.mdx
  src/app/docs/components/button/three-d-button/page.mdx
  src/app/docs/components/toggle/page.mdx
  src/app/docs/page.mdx
  src/app/page.tsx
  src/components/ComponentCards.tsx
  src/components/PreviewCode/HoverAnimationButtons.tsx
  src/components/cards/AnimationCards.tsx
  src/components/cards/ButtonCards.tsx
  src/components/cards/HoverAnimationCards.tsx
  src/components/cards/ToggleCards.tsx
  src/showcase/animations/SkewedInfiniteScroll.tsx
  src/showcase/animations/hover/HoverJiggleButton.tsx
  src/showcase/animations/hover/HoverPopButton.tsx
  src/showcase/animations/hover/HoverTadaButton.tsx
  src/showcase/animations/hover/HoverVibrateButton.tsx
  src/showcase/components/button/HeartbeatButton.tsx
  src/showcase/components/button/StitchesButton.tsx
  src/showcase/components/button/ThreeDButton.tsx
  src/styles/tailwind.css
Labels: chore

#80 updated the HeartbeatButton to say 'Syntax UI' and updated the padding to match the other buttons / updated the docs to reflect change
  src/app/docs/components/button/heartbeat-button/page.mdx
  src/showcase/components/button/HeartbeatButton.tsx
Labels: enhancement

#102 Update Components code using new component
  src/app/docs/components/button/3d-button/page.mdx
  src/app/docs/components/button/neubrutalism-button/page.mdx
  src/app/docs/components/button/stitches-button/page.mdx
  src/app/docs/components/button/three-d-button/page.mdx
  src/app/docs/components/features/page.mdx
  src/app/docs/components/footer/page.mdx
  src/app/docs/components/loaders/bounce/page.mdx
  src/app/docs/components/loaders/classic/page.mdx
  src/app/docs/components/loaders/neon-glow/page.mdx
  src/app/docs/components/loaders/orbiting/page.mdx
  src/app/docs/components/loaders/pulsating-dots/page.mdx
  src/app/docs/components/loaders/pulsating-gradient/page.mdx
  src/app/docs/components/loaders/ripple/page.mdx
  src/app/docs/components/loaders/rotating-dots/page.mdx
  src/app/docs/components/loaders/spinning-cube/page.mdx
  src/app/docs/components/loaders/staggered-fade/page.mdx
  src/app/docs/components/pricing/page.tsx
  src/app/docs/components/tabs/page.mdx
  src/app/docs/components/toggle/neobrutalism-toggle/page.mdx
  src/app/docs/components/toggle/neubrutalism-toggle/page.mdx
  src/app/docs/components/toggle/simple-toggle/page.mdx
  src/app/docs/effects/image-fade/page.mdx
  src/components/BackButton.tsx
  src/components/ComponentPreview.tsx
  src/components/mdx.tsx
  src/showcase/components/button/3DButton.tsx
  src/showcase/components/tabs/SimpleTabs.tsx
  src/showcase/components/toggle/NeubrutalismToggle.tsx
  src/showcase/ui-group/ButtonCards.tsx
  src/showcase/ui-group/ComponentCards.tsx
  src/showcase/ui-group/ToggleCards.tsx
Labels: enhancement

#104 fix: updating CONTIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#109 feat: added customLabels support for pages, layouts, docs, showcases, and components
  .vscode/settings.json
Labels: enhancement
